version: '3.6'

services:
  webapp:
    ports:
      - ${SERVER_PORT}:3000
    build:
      context: .
      dockerfile: etc/Dockerfile
    volumes:
      - /usr/src/app
    env_file:
      - .env
    restart: always